server:
  port: 8010
spring:
  kafka:
    topic:
      name: orders
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringDeserializer
    value-serializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="alice" password="alice-secret";